version: 1.2
workflows:
   -  name: Asm2AsmAligner
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/asm2asm_aligner.wdl
   -  name: ProduceFai
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/produce_fai.wdl
   -  name: DeepVariantScattered
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/variant_calling/deep_variant_scattered.wdl
   -  name: ProjectBlocks
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/other/project_blocks.wdl
   -  name: LongReadAlignerScattered
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/long_read_aligner_scattered.wdl
   -  name: LongReadAlignerSecphase
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/long_read_aligner_secphase.wdl
   -  name: LongReadAlignerScatteredPaf
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/long_read_aligner_scattered_paf.wdl
   -  name: UnionBedFiles
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/other/union_bed_files.wdl
   -  name: SubtractBedFiles
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/other/subtract_bed_files.wdl
   -  name: Bam2Paf
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/bam2paf.wdl
   -  name: BamCoverage
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/coverage/bam_coverage.wdl
   -  name: CalMD
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/calmd.wdl
   -  name: ConcatAssemblies
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/alignment/concat_assemblies.wdl
   -  name: GenerateWig
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/coverage/generate_wig.wdl
   -  name: Wig2TDF
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/coverage/wig2tdf.wdl
   -  name: DeepVariant
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/variant_calling/deep_variant.wdl
   -  name: PepperMarginDeepVariantScattered
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/variant_calling/pepper_margin_deep_variant_scattered.wdl
   -  name: ProjectFlaggerFinalBed
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/project_flagger_final_bed.wdl
   -  name: ProjectBlocksForFlagger
      subclass: WDL
      primaryDescriptorPath: /wdls/tasks/other/project_blocks_for_flagger.wdl
   -  name: HMMFlaggerEndToEnd
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/hmm_flagger_end_to_end.wdl
   -  name: HMMFlaggerEndToEndWithMapping
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/hmm_flagger_end_to_end_with_mapping.wdl
